---
inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "bin/octodown"

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/HashTransformValues:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashEachMethods:
  Enabled: true
