---
sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler
  - gem update --system
  - sudo apt-get install -y libicu-dev build-essential
script:
  - bundle exec rake
rvm:
  - '2.2.7'
  - '2.3.7'
  - '2.4.4'
  - '2.5.1'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: '2.2.7'
